#!/usr/bin/env ruby

require "fileutils"
require "yaml"
require "timeout"
require "csv"
require("byebug") if RUBY_PLATFORM.include?("darwin")
require "shellwords"
require "curl"
require "json"
require "parallel"
require "digest"

class VoiceGenerator
  attr_reader :label, :content, :locale

  def initialize(label:, content:, locale:)
    @label = label
    @content = content
    @locale = locale
  end

  def digest
    Digest::MD5.hexdigest(content)[0, 4]
  end

  def create_voice
    # for this command to works, you need to set
    # GOOGLE_APPLICATION_CREDENTIALS
    # the google application need to have cloud speech api enabled
    puts "GENERATING VOICE FOR #{content}"
    system "echo #{Shellwords.escape(content)} | yarn run tts #{Shellwords.escape(filename)} --language #{gcp_language} --service gcp --voice #{gcp_profile}"
  end

  def perform
    unless File.exists?(filename)
      create_voice
    end

    relative_filename
  end

  def gcp_language
    # https://cloud.google.com/text-to-speech/docs/voices
    case locale
    when "en" then "en-US"
    when "vi" then "vi-VN"
    when "es" then "es-ES"
    when "zh-CN" then "zh-CN"
    end
  end

  def gcp_profile
    case locale
    when "en" then "en-US-Neural2-E"
    when "vi" then "vi-VN-Wavenet-D"
    when "es" then "es-ES-Wavenet-C"
    when "zh-CN" then "cmn-CN-Standard-D"
    end
  end

  def relative_filename
    "audio/#{locale}/#{identifier}-#{digest}.mp3"
  end

  def identifier
    label&.gsub(/[^0-9a-z]/i, '-')
  end

  def filename
    File.expand_path(relative_filename, __dir__).tap do |name|
      FileUtils.mkdir_p(File.dirname(name))
    end
  end
end

class AudioUpdator
  def dict
    @dict ||= load_dict
  end

  def dict_filename
    File.expand_path("./dict.yaml", __dir__)
  end

  def load_dict
    if File.exists?(dict_filename)
      File.open(dict_filename, "r") { |f| YAML::load f }
    else
      {}
    end
  end

  def sorted_words
    dict.to_a.sort_by { |english, word| -word["frequency"].to_i }
  end

  def parallel_map(collection, &block)
    if ENV["DEBUG"]
      collection.map(&block)
    else
      Parallel.map(collection, &block)
    end
  end

  def perform
    # first use parallel to trigger parallel translation
    # this won't change the result, perhaps due to parallel forking processes
    list = parallel_map(sorted_words) do |_, word|
      perform_on_single_word(word)
    end

    CSV.open(audio_csv_filename, "w") do |csv|
      list.each do |row|
        csv << row
      end
    end
  end

  def perform_on_single_word(word)
    [
      VoiceGenerator.new(label: "vietnamese", content: "tiếng việt", locale: "vi").perform,
      VoiceGenerator.new(label: word["english"], content: word["vietnamese"], locale: "vi").perform,
      VoiceGenerator.new(label: "english", content: "tiếng anh", locale: "vi").perform,
      VoiceGenerator.new(label: word["english"], content: word["english"], locale: "en").perform,
      VoiceGenerator.new(label: "english-forms", content: "các hình thái khác trong tiếng anh", locale: "vi").perform,
      VoiceGenerator.new(label: word["english"], content: word["inflections"], locale: "en").perform,
      VoiceGenerator.new(label: "spanish", content: "tiếng tây ban nha", locale: "vi").perform,
      VoiceGenerator.new(label: word["english"], content: word["spanish"], locale: "es").perform,
      VoiceGenerator.new(label: "chinese", content: "tiếng trung quốc", locale: "vi").perform,
      VoiceGenerator.new(label: word["english"], content: word["chinese"], locale: "zh-CN").perform,
      VoiceGenerator.new(label: "example", content: "các ví dụ", locale: "vi").perform,
      VoiceGenerator.new(label: word["example_english"], content: word["example_vietnamese"], locale: "vi").perform,
      VoiceGenerator.new(label: word["example_english"], content: word["example_english"], locale: "en").perform,
      VoiceGenerator.new(label: word["example_english"], content: word["example_spanish"], locale: "es").perform,
      VoiceGenerator.new(label: word["example_english"], content: word["example_chinese"], locale: "zh-CN").perform,
    ].map do |name|
      "https://storage.googleapis.com/passivon/#{name}"
    end
  end

  def audio_csv_filename
    File.expand_path("audio/vocabulary_index.csv", __dir__)
  end
end

AudioUpdator.new.perform
