#!/usr/bin/env ruby

class AudioUploader
  def perform
    Dir.chdir(__dir__) do
      system "gsutil -m cp -n -r audio gs://passive-english"
      system "gsutil -m cp audio/index.csv gs://passive-english/audio/"
    end
  end
end

AudioUploader.new.perform
