#!/usr/bin/env ruby

class AudioUploader
  def perform
    Dir.chdir(__dir__) do
      system "gcloud alpha storage cp -n -r audio gs://passivon"
      system "gcloud alpha storage cp audio/index.csv gs://passivon/audio/"
      system %{gsutil setmeta -h "Cache-Control:public, max-age=300" gs://passivon/audio/index.csv}
    end
  end
end

AudioUploader.new.perform
